version: '3.7'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root # todo
      MONGO_INITDB_ROOT_PASSWORD: rootpassword # todo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root # todo
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword # todo
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb

volumes:
  mongodb_data_container: