version: '3.7'
services:
  mongodb:
    image: mongo:4.2.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
  mongo-express:
    image: mongo-express:latest
    container_name: mongoui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    restart: unless-stopped
  
  predicting-glucose-levels:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: glucose
    depends_on:
      - mongodb
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ../predicting_glucose_levels:/home/glucose/predicting_glucose_levels      

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    command: predicting-glucose-levels

  prefect-server:
    image: prefecthq/prefect:2.10.17-python3.11
    container_name: prefect-server
    restart: unless-stopped
    volumes:
      - prefect:/root/.prefect
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
    ports:
      - 4200:4200

  prefect-agent:
    image: prefecthq/prefect:2.10.17-python3.11
    container_name: prefect-agent
    restart: unless-stopped
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "agent", "start", "-q", "default"]
    environment:
      - PREFECT_API_URL=${PREFECT_API_URL}
    depends_on:
      - prefect-server      

volumes:
  mongodb_data:
  prefect:

networks:
  default:
    name: glucose-network