version: '3.7'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    env_file:
      - ../.env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    restart: unless-stopped
  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
    env_file:
      - ../.env
    depends_on:
      - mongodb
    restart: unless-stopped
  
  predicting-glucose-levels:
    image: predicting-glucose-levels:latest
    depends_on:
      - mongodb
    restart: unless-stopped
    env_file:
      - ../.env
volumes:
  mongodb_data_container: