name: build
on: [pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'poetry'        
    - name: Install poetry
      run: pipx install poetry
    # Need llvm for package
    - run: |
        SUDO add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
        sudo apt-get install llvm-10
    - run: poetry install
    - run: poetry run black --check --verbose .
    - run: poetry run isort --check .
    - run: poetry run pytest      