name: build
on: [pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: curl -sSL https://install.python-poetry.org | python3 -
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8.10'
        cache: 'poetry'
    - run: poetry config virtualenvs.create false
    - run: poetry install
    - run: poetry run black --check --verbose .
    - run: poetry run isort . --check --profile black
    - run: poetry run pytest
      env:
        PYTEST_ADDOPTS: "--color=yes"
      