name: build
on: [pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'poetry'
    - run: poetry export --without-hashes --format=requirements.txt > requirements.txt
    - run: pip install -r requirements.txt
    - run: black --check --verbose .
    - run: isort --check .
    - run: pytest