name: Job template
on: 
  workflow_call:
defaults:
  run:
    shell: bash
jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install