name: Job template
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install